package burp_injector.event.model;

public enum RegexTargetsModelEvent {
    TARGET_EDITOR_STATE_CHANGED,
    TARGET_CAPTURE_GROUP_CHANGED,
    TARGET_REGEX_CHANGED,
    TARGET_NAME_CHANGED,
    TARGET_ID_CHANGED,
    LAST_TARGET_ID_CHANGED,
    TARGET_SAVED,
    TARGET_DELETED,
    LAST_SAVE_ERROR_CHANGED, TARGET_STACK_CHANGED
}
