package burp_injector.event.controller;

public enum InjectorConfigControllerEvent {
    TEST_REQUEST_ADDED,
    NEW_RULE,
    SAVE_RULE,
    DELETE_RULE,
    CANCEL_RULE,

    SET_TARGET_METHOD_AUTO,
    SET_TARGET_METHOD_CUSTOM_AUTO,
    SET_TARGET_METHOD_REGEX,

    SET_OUTPUT_STDOUT,
    SET_OUTPUT_STDERR,
    SCRIPT_TAB_CHANGED,

    ENCODE_SCRIPT_UPDATED,
    DECODE_SCRIPT_UPDATED,
    PAYLOAD_SCRIPT_UPDATED,
    TEST_PAYLOAD_UPDATED,
    SET_CUSTOM_AUTO_NAME_GENERATION,
    SCRIPT_EXECUTED,

    RULE_NAME_CHANGED,
    RULE_SCOPE_CHANGED,
    RULE_DESCRIPTION_CHANGED,
    RULE_ENABLED_CHANGED,
    CUSTOM_AUTO_REGEX_CHANGED,
    AUTO_NAME_CHANGED,
    CUSTOM_AUTO_NAME_CAPTURE_GROUP_CHANGED,
    CUSTOM_AUTO_VALUE_CAPTURE_GROUP_CHANGED,
    REGEX_NAME_CHANGED,
    REGEX_PATTERN_CHANGED,

    SAVE_TARGET,
    NEW_TARGET,
    DELETE_TARGET,
    CANCEL_TARGET,


    RULE_TARGET_AREA_REGEX_CHANGED,
    RULE_TARGET_CAPTURE_GROUP_CHANGED,
    RULES_ROW_SELECTION_UPDATE,
    RULES_TABLE_MODEL_CHANGED,
    TARGETS_ROW_SELECTION_UPDATE,
    TARGETS_TABLE_MODEL_CHANGED,
    REGEX_CAPTURE_GROUP_CHANGED

}
