package burp_injector.event.controller;

public enum RulesControllerEvent {
    RULES_ROW_SELECTION_UPDATE,
    CANCEL,
    DELETE,
    SAVE,
    NEW,
    CUSTOM_AUTO_AUTONAME_UPDATED,
    CUSTOM_AUTO_VALUE_CAPTURE_GROUP_UPDATED,
    CUSTOM_AUTO_NAME_CAPTURE_GROUP_UPDATED,
    CUSTOM_AUTO_REGEX_UPDATED,
    TARGET_METHOD_REGEX_SET,
    TARGET_METHOD_CUSTOM_AUTO_SET,
    TARGET_METHOD_AUTO_SET,
    ENABLED_UPDATED,
    TARGET_AREA_CAPTURE_GROUP_UPDATED,
    TARGET_AREA_REGEX_UPDATED,
    SCOPE_UPDATED,
    DESCRIPTION_UPDATED,
    NAME_UPDATED,
    TEST,
    CANCEL_TEST,
    RULES_TABLE_MODEL_UPDATE
}
