package burp_injector.event.controller;

public enum ScriptControllerEvent {
    DECODE_SCRIPT_UPDATED,
    PAYLOAD_SCRIPT_UPDATED,
    TEST_PAYLOAD_UPDATED,
    OUTPUT_FILE_STDERR_SELECTED,
    OUTPUT_FILE_STDOUT_SELECTED,
    SCRIPT_EXECUTE_TOGGLED,
    ACTIVE_SCRIPT_TAB_UPDATED,
    PYTHON_PATH_UPDATED,
    SCRIPT_EXPORT_CLICKED,
    SCRIPT_IMPORT_CLICKED,
    ENCODE_SCRIPT_UPDATED
}
